const $=id=>document.getElementById(id);
const areaExamples={"600034":{name:"Nungambakkam, Chennai",score:68,down:72,up:11,ping:34,loss:.3,text:"Network performance is mixed. Your area is currently usable, but upload performance is weaker than download performance."},"682002":{name:"Fort Kochi, Kerala",score:79,down:91,up:18,ping:29,loss:.1,text:"Network health looks good. Current signals are within the recent local range."},"400001":{name:"South Mumbai",score:74,down:86,up:21,ping:31,loss:.2,text:"Mostly healthy network conditions with occasional latency variation."}};
let selected=areaExamples["600034"];
function render(a){selected=a;$('selectedArea').textContent='AREA / '+a.name;$('areaScore').textContent=a.score;$('areaLabel').textContent=a.score>=80?'HEALTHY':a.score>=65?'MODERATE':'WEAK';$('down').textContent=a.down;$('up').textContent=a.up;$('ping').textContent=a.ping;$('loss').textContent=a.loss;$('areaText').textContent=a.text}
function search(){const q=$('areaInput').value.trim();if(!q){render(areaExamples["600034"]);return}const found=areaExamples[q]||{name:q,score:72,down:68,up:14,ping:35,loss:.4,text:"A preliminary local estimate is available. More anonymous measurements are needed before this area can be classified confidently."};render(found);location.hash='areas'}
$('checkArea').onclick=search;$('areaInput').addEventListener('keydown',e=>{if(e.key==='Enter')search()});
document.querySelectorAll('.provider').forEach(b=>b.onclick=()=>{document.querySelectorAll('.provider').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('updated').textContent='AGGREGATED / '+b.textContent});
$('sendReport').onclick=()=>{if(!$('consent').checked){$('reportMsg').textContent='Please confirm anonymous reporting.';return}$('reportMsg').textContent='REPORT QUEUED — NO ACCOUNT OR IP STORED.';$('consent').checked=false};
$('nationalScore').textContent='73';$('nationalLabel').textContent='MOSTLY HEALTHY';$('reports').textContent='38';$('areasCount').textContent='1,432';$('updated').textContent='JUST NOW';$('ticker').textContent='LIVE FEED · Jio / Chennai · stable · Airtel / Bengaluru · healthy · Vi / Kochi · mixed · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});render(selected);
